controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_control:
      type: forward_command_controller/ForwardCommandController

    velocity_control:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_control:
  ros__parameters:
    joints:
      - lift_joint
    interface_name: position
    state_interfaces:
      - position
      - velocity
      
velocity_control:
  ros__parameters:
    joints:
      - lift_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity

